### ISSUE TITLE
FOIA.gov blocking request?

### ISSUE THREAD

**Issue by Balanc3** [drzax/clinton-email#1]
Seems like I could only get half way through then I started getting blocked. Got error: connect ETIMEDOUT 96.127.51.81:443 

Is there a way to wait then continue from the last set I received? 

I only got 25,951 documents. From what I can tell there are 129098 in total. I'm guessing any normal WAF would eventually block this request.

Did you have this issue?

**Comment by drzax** [comment]
I did a fresh full download over night and didn't run into this issue. Might be an issue with your connection?

In any case, I've pushed an update so that it won't re-download docs it already has in the `documents` folder. 

Also, I've pushed an update to the readme recommending https://github.com/wsjdata/clinton-email-cruncher over this tool—it's way better.
